create table tb_worker (id_long int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id_long));
create table tb_worker (id_long int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id_long));
create table tb_worker (id_long int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id_long));
create table tb_worker (id_long int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id_long));
create table tb_worker (id int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id));
